apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-class
  labels:
    app.kubernetes.io/component: operator
value: 2100000
globalDefault: false
description: "Scheduling priority of api-gateway component. Must not be blocked by unschedulable user workloads."
