resources:
  - GroupVersionKind:
      group: gateway.kyma-project.io
      version: v2alpha1
      kind: APIRule
  - GroupVersionKind:
      group: networking.istio.io
      version: v1beta1
      kind: VirtualService
    ControlledList:
      - name: "istio-healthz"
        namespace: "istio-system"
