# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apirules.gateway.kyma-project.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: kyma-system
          name: api-gateway-webhook-service
          port: 9443
          path: /convert
      conversionReviewVersions:
        - v1beta1
        - v2alpha1
        - v2
