name: PART 1 Release Api Gateway

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release Tag"
        default: ""
        required: true
      since: # ta wartość jest potrzebna dla drugiego Workflowu
        description: "Changelog since"
        default: ""
        required: false

jobs:
  relese-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #token: ${{ secrets.GOAT_BOT_REPO_ACCESS }} #The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands. The token is removed during post-job cleanup.

      - name: Determine if this is a patch release
        id: check_patch
        run: |
          if [[ "${{ github.event.inputs.name }} }}" =~ ^[0-9]+\.[0-9]+\.[1-9][0-9]*$ ]]; then
            echo "is_patch=true" >> $GITHUB_ENV
          else
            echo "is_patch=false" >> $GITHUB_ENV

      - name: Create a release branch #(if not a patch release)
        if: env.is_patch == 'false'
        run: |
          major_minor=$(echo "${{ github.event.inputs.name }}" | grep -Eo '^[0-9]+\.[0-9]+')
          branch_name="release-$major_minor"
          echo "branch_name=$branch_name" >> $GITHUB_ENV 
          git checkout -b "$branch_name"
          git push origin "$branch_name"

      - name: Update sec-scanners-config and dependabot config image path and image tag 
        env:
          IMAGE: " - europe-docker.pkg.dev/kyma-project/prod/api-gateway/releases/api-gateway-manager"
          IMAGE_TAG: ${{ github.event.inputs.name }}
          REL_BRANCH: ${{ env.branch_name}}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git fetch origin
          git checkout -f release/sec-scanners-config
          git reset --hard origin/main
          sed -i "s|.*api-gateway-manager:.*|$IMAGE\:$IMAGE_TAG|g" sec-scanners-config.yaml
          git add .
          if git diff-index --quiet HEAD; then
            echo "Error: No changes detected"
            exit 1
          fi
          git commit -m "release: update sec-scanners-config.yaml" -m "Generated by GitHub Actions"
          git push -f -u origin release/sec-scanners-config
          gh pr create --base $REL_BRANCH --head release/sec-scanners-config --fill || true 