name: UI Tests

on:
  workflow_call:

jobs:
  run-ui-tests:
    name: Run UI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/load-manager-image
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Tests
        run: |
          sudo echo "127.0.0.1 local.kyma.dev" | sudo tee -a /etc/hosts
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | sudo bash
          IMG=api-gateway-manager:PR-${{ github.event.number }} ./tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh prod
      - uses: actions/upload-artifact@v4
        if: always()
        name: Export Cypress output
        with:
          name: cypress
          path: tests/ui/tests/cypress/
