name: Deploy VitePress site to Pages
description: |-
  This workflow creates a local instance of kyma-project.io website and adds the documentation from the branch to this instance.
  To run this workflow you need to
  - Have Github pages enabled in your fork.
  - Have the pages environment set to `docs/*` branches.
  - Have the branch the deployment should take place from in the `docs/*` format. Alternatively it can be manually dispatched.
on:
  push:
    branches: ["docs/*"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Clone Kyma project
        shell: bash
        run: |-
          git clone https://github.com/kyma-project/kyma
      - name: Copy external content (documentation of modules)
        shell: bash
        run: |-
          cd kyma/hack
          sed -i 's|mkdir -p "\$TARGET_USER"|mkdir -p "\$TARGET_USER" \&\& rm -d "\$TARGET_USER"|g' ./copy_external_content.sh
          sed -i '/mkdir -p "\$TARGET_ASSETS"/d' ./copy_external_content.sh
          bash ./copy_external_content.sh
      - name: Replace api-gateway external-content with current branch version
        shell: bash
        run: |-
          rm -rf ./kyma/docs/external-content/api-gateway
          mkdir -p ./kyma/docs/external-content/api-gateway
          cp docs -r ./kyma/docs/external-content/api-gateway/docs
      - name: Install dependencies
        run: |-
          cd kyma
          npm install
      - name: Build with VitePress
        shell: bash
        run: |-
          cd kyma
          sed -i "s|base: '/'|base: '/${{ github.event.repository.name }}/'|" ./.vitepress/config.mjs
          ./move_to_public.sh
          git --no-pager diff
          npx vitepress build
          rm -rf ./docs/public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: kyma/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
