# This workflow is responsible for all kinds of integration tests run on pull request.
# Those tests depend on a container image so in the first job we wait for the image build to succeed.

name: Pull Request integration tests

on:
  pull_request_target:
    types: [synchronize, opened, reopened, ready_for_review]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "tests/performance/**"
      - "OWNERS"
      - "CODEOWNERS"
      - "sec-scanners-config.yaml"
      - ".github/**" #Ignoring since build job isn't triggered on the workflow directory changes
    branches:
      - fix-gha
      - 'release-**'

jobs:
  wait-for-image-build:
    environment: ${{ (github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'OWNER') && internal || restricted }}
    name: Wait for image build
    runs-on: ubuntu-latest
    needs: check-access
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # This is dangerous without the environment check
      - uses: ./.github/actions/wait-for-job-succeed-or-fail
        with:
          job-name: 'pull-api-gateway-build'
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}

  api-gateway-upgrade-test:
    environment: ${{ (github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'OWNER') && internal || restricted }}
    name: Istio upgrade integration test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    needs: [check-access, wait-for-image-build]
    steps:
      - uses: actions/checkout@v4 # This is dangerous without the environment check
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/actions/upgrade-integration-test
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          OIDC_ISSUER_URL: ${{ secrets.OIDC_ISSUER_URL }}
        with:
          upgrade-image-name: "europe-docker.pkg.dev/kyma-project/dev/api-gateway-controller:PR-${{github.event.number}}"
